### ISSUE TITLE
Error on submit to Apple?

### ISSUE THREAD

**Issue by pj4533** [helpscout/HSAttachmentPicker#10]
I have the Helpscout Beacon integrated in our app, and recently submitting to Apple flags this error:

Invalid Document Configuration - Document Based Apps should support either the Document Browser (UISupportsDocumentBrowser = YES) or implement Open In Place (LSSupportsOpeningDocumentsInPlace = YES/NO). Visit https://developer.apple.com/document-based-apps/ for more information.

I think it is due to the HSAttachmentPicker, as that seems to be the only dependency that uses UIDocument.  Which setting does Helpscout recommend we put in the info.plist?

**Comment by jgritman** [comment]
Closing this as it doesn't appear related to HSAttachmentPicker after talking with PJ.
