### ISSUE TITLE
Swift updated project files

### ISSUE THREAD

**Issue by Elamuruga** [helpscout/HSAttachmentPicker#24]
Hai this is an amazing plugin. I am a beginner to IOS development could you please help me by converting this project and its files to **Swift**. It will be easy to understand and readable? Waiting for your response thanks in advance.

**Comment by ScottPetit** [comment]
I don't think we're going to do the work to convert this to Swift, seeing as how it should be fully annotated with what's null/nonnull and works just fine in Objective-C.
