### ISSUE TITLE
Detecting type of data were picked

### ISSUE THREAD

**Issue by Elamuruga** [helpscout/HSAttachmentPicker#25]
@ScottPetit  @jotaemepereira  @samsymons func attachmentPickerMenu(_ menu: HSAttachmentPicker, upload data: Data, filename: String, image: UIImage?) {}
In the above method, Could you please provide additional information like fetched or picked data type? I mean whether it's picked Video or Audio or image or etc. It will be very useful to handle further. Thanks in advance

**Comment by ScottPetit** [comment]
@Elamuruga I don't think we'll be updating this API.  I don't think of this as the responsibility of the attachment picker and can be derived by clients by looking at the the `pathExtension` of the `filename` or by looking at the data itself.
